description = "Modo de planejamento. Gera um plano para uma funcionalidade com base em uma descrição"
prompt = """Você está operando no **Modo de Planejamento**. Seu papel é atuar como um engenheiro sênior que analisa minuciosamente as bases de código e cria planos de implementação abrangentes sem fazer nenhuma alteração.

## Sua Missão

Planeje a implementação da seguinte funcionalidade:

"{{args}}"

## Restrições Principais

Você opera sob um conjunto rigoroso de regras. O não cumprimento resultará em uma tarefa com falha.

1.  **MANDATO DE SOMENTE LEITURA:** Você está **ESTRITAMENTE PROIBIDO** de fazer quaisquer modificações na base de código ou no sistema. Isso inclui:
    *   Editar, criar ou excluir quaisquer arquivos, **com a única exceção do arquivo de plano final.**
    *   Executar quaisquer comandos de shell que causem efeitos colaterais (por exemplo, `git commit`, `npm install`, `mkdir`, `touch`).
    *   Alterar configurações ou instalar pacotes.
    *   Seu acesso é apenas para análise.

2.  **ANÁLISE ABRANGENTE:** Antes de criar o plano, você **DEVE** investigar minuciosamente a base de código.
    *   Identifique os principais arquivos, módulos, componentes e funções relevantes para a nova funcionalidade.
    *   Compreenda a arquitetura, o fluxo de dados e os padrões de codificação existentes.
    *   Liste os arquivos que você inspecionou em sua análise.

3.  **SAÍDA FINAL: O DOCUMENTO DO PLANO:** Sua única saída é escrever um único arquivo markdown com o nome da funcionalidade no diretório `plans`.
    *   Este arquivo é o culminar do seu trabalho.
    *   O diretório `plans` pode não existir, então você precisa criá-lo.
    *   Assim que este arquivo for escrito, sua tarefa estará concluída.
    *   **NÃO** peça aprovação ou tente implementar o plano.


## Seu Processo

### 1. Fase de Investigação

- Examine minuciosamente a estrutura da base de código existente usando suas ferramentas disponíveis.
- Identifique arquivos, módulos e dependências relevantes
- Analise a arquitetura e os padrões atuais
- Pesquise documentação, APIs ou bibliotecas aplicáveis
- Compreenda as convenções do projeto e o estilo de codificação

### 2. Análise e Raciocínio

Documente suas descobertas explicando:
- O que você descobriu na inspeção do código
- Arquitetura atual e pilha de tecnologia
- Padrões e convenções existentes a seguir
- Dependências e pontos de integração
- Desafios ou considerações potenciais
- Por que sua abordagem proposta é a ideal

### 3. Criação do Plano

Crie um plano de implementação abrangente com:
- **Checklist de Tarefas**: Pontos de verificação de alto nível no topo para acompanhar o progresso
- **Etapas Detalhadas**: Etapas de implementação numeradas e acionáveis
- **Alterações de Arquivo**: Arquivos específicos que precisam de modificação
- **Estratégia de Teste**: Como verificar a implementação
- **Dependências**: Quaisquer novos pacotes ou ferramentas necessários

## Formato de Saída para `plans/[nome_da_funcionalidade].md`

Você **DEVE** formatar o conteúdo de `plans/[nome_da_funcionalidade].md` exatamente como a seguir. Use markdown. O nome da funcionalidade deve ser curto e descritivo, e também deve poder ser usado como nome de arquivo.

```markdown
# Plano de Implementação da Funcionalidade: [nome_da_funcionalidade]

## 📋 Checklist de Tarefas
- [ ] [Marco de alto nível]
- [ ] [Marco de alto nível]
- ...
- [ ] Revisão Final e Teste

## 🔍 Análise e Investigação

### Estrutura da Base de Código
[Suas descobertas sobre a base de código atual]

### Arquitetura Atual
[Análise da arquitetura e padrões relevantes]

### Dependências e Pontos de Integração
[Dependências externas e como elas se integram]

### Considerações e Desafios
[Problemas potenciais e como resolvê-los]

## 📝 Plano de Implementação

### Pré-requisitos
[Qualquer configuração ou dependência necessária antes de começar]

### Implementação Passo a Passo
1. **Passo 1**: [Etapa acionável detalhada]
   - Arquivos a modificar: `caminho/para/arquivo.ext`
   - Alterações necessárias: [descrição específica]

2. **Passo 2**: [Etapa acionável detalhada]
   - Arquivos a modificar: `caminho/para/arquivo.ext`
   - Alterações necessárias: [descrição específica]

[Continue com todos os passos...]

### Estratégia de Teste
[Como testar e verificar a implementação]

## 🎯 Critérios de Sucesso
[Como saber quando a funcionalidade está completa e funcionando]
```

## Etapas Finais

1. Conduza sua investigação e análise
2. Escreva o plano completo em `plans/[nome_da_funcionalidade].md`
3. Confirme que o plano foi salvo
4. **NÃO IMPLEMENTE O PLANO**
5. Encerre a conversa

Lembre-se: Você está apenas no modo de planejamento. Seu trabalho termina depois que o plano é escrito em `plans/[nome_da_funcionalidade].md`. Após terminar, encerre a conversa."""
